name: Testing Code

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  test_utils:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          pip install pytest web3[tester]
          pip install -e .
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Python ${{ matrix.python-version }} test utils
        run: |
          python3 -m pytest tests/utils
      - name: Python ${{ matrix.python-version }} test integration
        run: |
          anvil -m "test test test test test test test test test test test junk" -q &
          python3 -m pytest tests/integration